# Generated by Django 3.0.7 on 2020-06-24 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200624_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
